import { useEffect, useRef } from 'react';
import { CategoryChallenge } from '@/components/CategoryChallenge';
import { useActivityState, numberIn } from './useActivityState';
import { dbscan, kmeansTrace, normalize, pcaPoints, projection, samplePoints, silhouette, type Point } from './learningMath';

function NumericCheck({id,prompt,answer,explanation,onComplete}:{id:string;prompt:string;answer:number;explanation:string;onComplete:()=>void}){
  const [saved,setSaved]=useActivityState<{input:string;submitted:boolean}>(id,{input:'',submitted:false},(v):v is {input:string;submitted:boolean}=>!!v&&typeof v==='object'&&typeof (v as {input:unknown}).input==='string'&&typeof (v as {submitted:unknown}).submitted==='boolean');
  const correct=saved.input.trim()!==''&&Number.isFinite(Number(saved.input))&&Math.abs(Number(saved.input)-answer)<.015;
  const reported=useRef(false);
  useEffect(()=>{if(saved.submitted&&correct&&!reported.current){reported.current=true;onComplete();}},[saved.submitted,correct,onComplete]);
  return <section className="numeric-check"><h3>{prompt}</h3><form onSubmit={e=>{e.preventDefault();setSaved({...saved,submitted:true});}}><label htmlFor={id}>Your numerical answer</label><div className="answer-row"><input id={id} type="number" step="any" value={saved.input} onChange={e=>setSaved({input:e.target.value,submitted:false})}/><button className="button button-primary" disabled={saved.input.trim()===''}>Check calculation</button></div></form>{saved.submitted&&<div className={`feedback ${correct?'feedback-correct':'feedback-incorrect'}`} role="status"><p>{correct?`That calculation fits. ${explanation}`:`Revisit the quantities in the formula. ${explanation} Enter a revised answer and check it again.`}</p></div>}</section>;
}
const colors=['#0076c2','#c74b20','#8a50cb','#078067','#b37300'];
function Scatter({points,labels,centers,selected,eps,types}:{points:Point[];labels:number[];centers?:Point[];selected?:number;eps?:number;types?:string[]}){
  const x=(n:number)=>40+n*46,y=(n:number)=>310-n*28;
  return <div className="chart-frame"><svg viewBox="0 0 540 350" role="img" aria-label="Synthetic points on feature x and feature y axes. Cluster numbers, center crosses, and noise symbols are described below.">
    {[0,2,4,6,8,10].map(n=><g key={n}><line className="chart-grid-line" x1="40" x2="500" y1={y(n)} y2={y(n)}/><text className="chart-tick" x="27" y={y(n)+4} textAnchor="end">{n}</text><text className="chart-tick" x={x(n)} y="330" textAnchor="middle">{n}</text></g>)}
    <text className="chart-axis-label" x="270" y="348" textAnchor="middle">Feature x · arbitrary units</text>
    <text className="chart-axis-label" transform="translate(12 170) rotate(-90)" textAnchor="middle">Feature y</text>
    {selected!==undefined&&eps!==undefined&&<ellipse cx={x(points[selected].x)} cy={y(points[selected].y)} rx={eps*46} ry={eps*28} fill="none" stroke="currentColor" strokeDasharray="5 4"/>}
    {points.map((p,i)=><g key={i}>{labels[i]<0?<path d={`M${x(p.x)-4},${y(p.y)-4}l8,8m-8,0l8,-8`} stroke="var(--muted)" strokeWidth="2"/>:<><circle cx={x(p.x)} cy={y(p.y)} r={types?.[i]==='border'?7:8} fill={types?.[i]==='border'?'var(--surface)':colors[labels[i]%colors.length]} stroke={colors[labels[i]%colors.length]} strokeWidth="2"/><text x={x(p.x)} y={y(p.y)+3.5} textAnchor="middle" fill={types?.[i]==='border'?'var(--ink)':'white'} fontSize="10">{labels[i]+1}</text></>}{selected===i&&<circle cx={x(p.x)} cy={y(p.y)} r="13" stroke="currentColor" fill="none" strokeWidth="2"/>}</g>)}
    {centers?.map((p,i)=><g key={i}><path d={`M${x(p.x)-10},${y(p.y)}h20m-10,-10v20`} stroke="var(--ink)" strokeWidth="3"/><text className="chart-label" x={x(p.x)+12} y={y(p.y)-12}>C{i+1}</text></g>)}
  </svg></div>;
}
function Scaling({onComplete}:{onComplete:()=>void}){
  const [income,setIncome]=useActivityState('income',73000,numberIn(12000,98000));
  return <><p>Predict which income maps to zero under each transformation. Then move the income control. The reference minimum, maximum, mean, and standard deviation stay fixed at the lecture’s values.</p><section className="visual-lab"><label className="range-label">Income <strong>{income.toLocaleString()}</strong><input aria-label="Income" type="range" min="12000" max="98000" step="1000" value={income} onChange={e=>setIncome(Number(e.target.value))}/></label><div className="metric-grid"><div><span>Min-max · range 12,000–98,000</span><strong>{normalize(income,12000,98000).toFixed(3)}</strong><code>({income} − 12000) / 86000</code></div><div><span>Z-score · μ = 54,000; σ = 16,000</span><strong>{((income-54000)/16000).toFixed(3)}</strong><code>({income} − 54000) / 16000</code></div></div><p>Min-max zero means the reference minimum. Z-score zero means the reference mean. Neither transformation changes the units of the original observation stored in your source data.</p><button className="button button-secondary" onClick={()=>setIncome(73000)}>Reset income</button></section><NumericCheck id="scaling-calculation" prompt="Fresh case: scale 30 from a range of 10 to 50 into [0, 1]." answer={.5} explanation="(30 − 10) / (50 − 10) = 20 / 40 = 0.5." onComplete={onComplete}/></>;
}
function PCA({onComplete}:{onComplete:()=>void}){
  const [angle,setAngle]=useActivityState('pca-angle',0,numberIn(0,180));const data=projection(pcaPoints,angle);
  const x=(v:number)=>260+v*43,y=(v:number)=>170-v*32;
  return <><p>Find a direction that keeps at least 95% of the variance in this synthetic, centered point cloud. Compare perpendicular reconstruction error at 0°, about 40°, and 130°.</p><section className="visual-lab"><label className="range-label">Projection angle <strong>{angle}°</strong><input aria-label="Projection angle" type="range" min="0" max="180" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></label><div className="chart-frame"><svg viewBox="0 0 520 350" role="img" aria-label={`PCA projection at ${angle} degrees; ${(data.retained*100).toFixed(1)} percent variance retained. Dashed segments show reconstruction errors.`}><line className="chart-grid-line" x1="30" x2="490" y1={y(0)} y2={y(0)}/><line className="chart-grid-line" x1={x(0)} x2={x(0)} y1="10" y2="320"/><line stroke="var(--course-accent)" strokeWidth="2" x1={x(data.center.x-data.unit.x*4.5)} y1={y(data.center.y-data.unit.y*4.5)} x2={x(data.center.x+data.unit.x*4.5)} y2={y(data.center.y+data.unit.y*4.5)}/>{pcaPoints.map((p,i)=><g key={i}><line x1={x(p.x)} y1={y(p.y)} x2={x(data.projected[i].x)} y2={y(data.projected[i].y)} stroke="var(--muted)" strokeDasharray="4 3"/><circle cx={x(p.x)} cy={y(p.y)} r="5" fill="var(--course-accent)"/><rect x={x(data.projected[i].x)-3} y={y(data.projected[i].y)-3} width="6" height="6" fill="var(--ink)"/></g>)}{[-4,-2,0,2,4].map(n=><text key={n} className="chart-tick" x={x(n)} y="330" textAnchor="middle">{n}</text>)}<text className="chart-axis-label" x="260" y="348" textAnchor="middle">Centered feature x · feature y vertical</text></svg></div><div className="metric-grid"><div><span>Variance retained</span><strong>{(100*data.retained).toFixed(1)}%</strong></div><div><span>Squared reconstruction error</span><strong>{data.error.toFixed(2)}</strong></div></div><p>Circles are observations; squares are reconstructed points. Dashed segments measure what this one-dimensional representation loses.</p><button className="button button-secondary" onClick={()=>setAngle(0)}>Reset projection</button></section><NumericCheck id="pca-calculation" prompt="If total variance is 20 and discarded variance is 3, what percentage is retained?" answer={85} explanation="The retained variance is 17. Divide 17 by 20 and multiply by 100 to obtain 85%." onComplete={onComplete}/></>;
}
function KMeans({onComplete}:{onComplete:()=>void}){
  const [k,setK]=useActivityState('kmeans-k',3,(v):v is number=>numberIn(2,5)(v)&&Number.isInteger(v));
  const [step,setStep]=useActivityState('kmeans-cycle',0,(v):v is number=>numberIn(0,12)(v)&&Number.isInteger(v));
  const trace=kmeansTrace(samplePoints,k,12), current=trace[step];const converged=step>0&&Math.abs(current.sse-trace[step-1].sse)<1e-8;
  return <><p>Before taking a step, predict whether SSE will rise or fall. Each step updates the centers from their assigned members, then assigns observations to the nearest updated center.</p><section className="visual-lab"><label className="range-label">Number of clusters <strong>{k}</strong><input aria-label="Number of clusters" type="range" min="2" max="5" value={k} onChange={e=>{setK(Number(e.target.value));setStep(0);}}/></label><Scatter points={samplePoints} labels={current.labels} centers={current.centers}/><div className="metric-grid" aria-live="polite"><div><span>Completed update cycles</span><strong>{step}</strong></div><div><span>SSE · squared units</span><strong>{current.sse.toFixed(2)}</strong></div></div><div className="activity-actions"><button className="button button-secondary" disabled={step===0} onClick={()=>setStep(step-1)}>Previous step</button><button className="button button-primary" disabled={step===12||converged} onClick={()=>setStep(step+1)}>Update centers</button><button className="button button-quiet" onClick={()=>setStep(0)}>Reset algorithm</button></div><p role="status">{converged?'The centers have stabilized for this initialization. Try a different k and compare.':step===0?'Initial centers are marked with crosses. Point numbers indicate assigned clusters.':'The means have moved toward their assigned observations. Compare the new SSE with the previous step.'}</p><div className="cluster-counts">{current.centers.map((_,j)=><span key={j}>Cluster {j+1}: {current.labels.filter(l=>l===j).length} points</span>)}</div><small>39 fixed synthetic points; deterministic initialization. Empty centers are retained. This example is not the GeoNames dataset.</small></section><NumericCheck id="kmeans-calculation" prompt="One cluster contains values 2, 4, and 6. What is its new center?" answer={4} explanation="The mean is (2 + 4 + 6) / 3 = 4." onComplete={onComplete}/></>;
}
function Density({onComplete}:{onComplete:()=>void}){
  const [eps,setEps]=useActivityState('dbscan-eps',.8,numberIn(.2,2.5));
  const [min,setMin]=useActivityState('dbscan-min',4,(v):v is number=>numberIn(2,8)(v)&&Number.isInteger(v));
  const [selected,setSelected]=useActivityState('dbscan-point',0,(v):v is number=>numberIn(0,38)(v)&&Number.isInteger(v));
  const result=dbscan(samplePoints,eps,min);
  return <><p>Predict what happens to noise when ε grows. Inspect point 37, an isolated observation, and compare its neighborhood with point 1.</p><section className="visual-lab"><div className="control-grid"><label>Radius ε <strong>{eps.toFixed(1)}</strong><input aria-label="Radius epsilon" type="range" min=".2" max="2.5" step=".1" value={eps} onChange={e=>setEps(Number(e.target.value))}/></label><label>Minimum points <strong>{min}</strong><input aria-label="Minimum points" type="range" min="2" max="8" value={min} onChange={e=>setMin(Number(e.target.value))}/></label><label>Inspect point<select aria-label="Inspect point" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{samplePoints.map((_,i)=><option value={i} key={i}>Point {i+1}</option>)}</select></label></div><Scatter points={samplePoints} labels={result.labels} types={result.types} selected={selected} eps={eps}/><p role="status"><strong>Point {selected+1}: {result.types[selected]}.</strong> Its neighborhood contains {result.neighbors[selected].length} points including itself; the core threshold is {min}.</p><div className="cluster-counts"><span>{result.clusters} clusters</span><span>{result.types.filter(t=>t==='core').length} core</span><span>{result.types.filter(t=>t==='border').length} border</span><span>{result.types.filter(t=>t==='noise').length} noise</span></div><p>Filled numbered circles are core points; hollow numbered circles are border points; × marks noise. The dashed neighborhood looks elliptical because the chart uses different horizontal and vertical scales.</p><button className="button button-secondary" onClick={()=>{setEps(.8);setMin(4);setSelected(0);}}>Reset density settings</button></section><NumericCheck id="density-calculation" prompt="MinPts is 4, including the point itself. How many other neighbors does it need to be core?" answer={3} explanation="The point itself contributes one, so three other observations reach the threshold of four." onComplete={onComplete}/></>;
}
function Silhouette({onComplete}:{onComplete:()=>void}){
  const [a,setA]=useActivityState('silhouette-a',2,numberIn(.5,10));const [b,setB]=useActivityState('silhouette-b',6,numberIn(.5,10));
  const s=silhouette(a,b);
  return <><p>Make the point closer to another group than to its own. Watch the sign of the score. These are synthetic average distances, not measurements from a dataset.</p><section className="visual-lab"><div className="control-grid"><label>Within-cluster distance a <strong>{a}</strong><input aria-label="Within-cluster distance" type="range" min=".5" max="10" step=".5" value={a} onChange={e=>setA(Number(e.target.value))}/></label><label>Nearest other-cluster distance b <strong>{b}</strong><input aria-label="Other-cluster distance" type="range" min=".5" max="10" step=".5" value={b} onChange={e=>setB(Number(e.target.value))}/></label></div><div className="formula-strip"><span>s = (b − a) / max(a, b)</span><strong>{s.toFixed(3)}</strong></div><p aria-live="polite">{s>0?'The point is closer on average to its own cluster.':s<0?'Another cluster is closer on average. Inspect this assignment.':'Both average distances are equal. The point sits on the boundary according to this score.'}</p></section><NumericCheck id="silhouette-calculation" prompt="A fresh point has a = 1 and b = 5. Calculate its silhouette." answer={.8} explanation="(5 − 1) / max(1, 5) = 4 / 5 = 0.8." onComplete={onComplete}/></>;
}
const syntheticHours=[1,2,3,3,7,8,9,10,12,12,14,15,16,18,20,21,22,23];
function EDA({onComplete}:{onComplete:()=>void}){
  const [hour,setHour]=useActivityState('eda-hour',0,(v):v is number=>numberIn(0,23)(v)&&Number.isInteger(v));
  const [bins,setBins]=useActivityState('eda-bins',6,(v):v is number=>[3,6,12].includes(v as number));
  const selected=syntheticHours.filter(h=>h>=hour),width=24/bins;
  const counts=Array.from({length:bins},(_,i)=>selected.filter(h=>h>=i*width&&h<(i+1)*width).length);
  return <><p>This synthetic sample contains 18 event hours. It is only a demonstration of filtering and binning, with no claims about real crime patterns.</p><section className="visual-lab"><div className="control-grid"><label>Keep observations from hour <strong>{hour}:00</strong><input aria-label="Minimum hour" type="range" min="0" max="23" value={hour} onChange={e=>setHour(Number(e.target.value))}/></label><label>Number of bins<select aria-label="Histogram bins" value={bins} onChange={e=>setBins(Number(e.target.value))}>{[3,6,12].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="histogram" role="img" aria-label={`Histogram of ${selected.length} synthetic observations. Counts by interval follow.`}>{counts.map((count,i)=><div key={i}><strong>{count}</strong><div className="histogram-bar" style={{height:count*22}}/><span>{i*width}–{(i+1)*width-1}h</span></div>)}</div><p><strong>{selected.length} of 18 observations remain.</strong> Changing the bins reorganizes this same subset; filtering changes which observations are counted.</p><details><summary>Inspect the synthetic hours</summary><p>{selected.join(', ')}</p></details></section><NumericCheck id="eda-calculation" prompt="You divide the full 24-hour range into 6 equal-width bins. How many hours does each bin span?" answer={4} explanation="24 / 6 = 4 hours per interval." onComplete={onComplete}/></>;
}
function LabRecord({onComplete}:{onComplete:()=>void}){
  const [notes,setNotes]=useActivityState('lab-record',{method:'KMeans',parameters:'',observation:'',limitation:''},(v):v is {method:string;parameters:string;observation:string;limitation:string}=>!!v&&typeof v==='object'&&['method','parameters','observation','limitation'].every(k=>typeof (v as Record<string,unknown>)[k]==='string'));
  const [saved,setSaved]=useActivityState('lab-record-confirmed',false,(v):v is boolean=>typeof v==='boolean');
  const reported=useRef(false),valid=[notes.parameters,notes.observation,notes.limitation].every(s=>s.trim().length>=10);
  useEffect(()=>{if(saved&&valid&&!reported.current){reported.current=true;onComplete();}},[saved,valid,onComplete]);
  return <section className="visual-lab"><h3>Your experimental record</h3><p>After a notebook run, record what you measured and what it means. Notes stay in this browser and are not submitted to an instructor. Saving records completion of this reflection, not verification of your experiment.</p><label>Method<select value={notes.method} onChange={e=>{setSaved(false);setNotes({...notes,method:e.target.value});}}>{['KMeans','GaussianMixture','SpectralClustering','AgglomerativeClustering','DBSCAN','MeanShift'].map(m=><option key={m}>{m}</option>)}</select></label>{(['parameters','observation','limitation'] as const).map(key=><label className="lab-note" key={key}>{key==='parameters'?'Parameters, scaling, and measured runtime':key==='observation'?'Observed result and your explanation':'A limitation or next comparison'}<textarea rows={3} value={notes[key]} onChange={e=>{setSaved(false);setNotes({...notes,[key]:e.target.value});}}/></label>)}<button className="button button-primary" disabled={!valid} onClick={()=>setSaved(true)}>Save reflection</button>{!valid&&<p>Write at least 10 characters in each field before saving.</p>}{saved&&<p role="status">Reflection saved in this browser. You can return and revise it.</p>}</section>;
}
export function CourseActivity({kind,onComplete}:{kind:string;onComplete:()=>void}){
  if(kind==='normalization')return <Scaling onComplete={onComplete}/>;
  if(kind==='pca')return <PCA onComplete={onComplete}/>;
  if(kind==='kmeans')return <KMeans onComplete={onComplete}/>;
  if(kind==='dbscan')return <Density onComplete={onComplete}/>;
  if(kind==='silhouette')return <Silhouette onComplete={onComplete}/>;
  if(kind==='eda')return <EDA onComplete={onComplete}/>;
  if(kind==='lab-record')return <LabRecord onComplete={onComplete}/>;
  const systems=kind==='systems';
  return <CategoryChallenge title={systems?'Which workload fits the decision?':'What information does the learner receive?'} introduction="These are new teaching examples. Choose a category, read the explanation, then continue." storageKey={`${kind}-practice`} onComplete={onComplete} categories={systems?['OLTP','Batch analytics','Streaming analytics']:['Supervised','Unsupervised','Reinforcement']} items={systems?[
    {id:'purchase',prompt:'Confirm one customer’s purchase and update the order record.',answer:'OLTP',explanation:'This is a short transaction involving a small number of records and an immediate response.'},
    {id:'report',prompt:'Compute last month’s sales by country for a report tomorrow morning.',answer:'Batch analytics',explanation:'The query aggregates many records, and its deadline tolerates a batch result.'},
    {id:'events',prompt:'Update an alert decision as each sensor event arrives.',answer:'Streaming analytics',explanation:'The result must react to new observations promptly rather than waiting for the next batch.'},
  ]:[
    {id:'sales',prompt:'Predict tomorrow’s sales from past days paired with observed sales totals.',answer:'Supervised',explanation:'Each input has a numerical target. This is supervised regression.'},
    {id:'groups',prompt:'Group unlabelled documents by their similarity.',answer:'Unsupervised',explanation:'No group labels are supplied. The grouping comes from patterns in the representation.'},
    {id:'robot',prompt:'A robot tries moves and receives a reward for reaching a destination.',answer:'Reinforcement',explanation:'The robot learns through the consequences of actions in an environment.'},
  ]}/>;
}
