import type { SourceReference } from '../types';
export interface Check { question: string; options: { id: string; label: string; feedback: string; correct?: boolean }[] }
export interface LessonSection { id: string; title: string; paragraphs: string[]; code?: string; table?: string[][] }
export interface Lesson {
  slug: string; title: string; summary: string; minutes: number; objectives: string[]; sources: SourceReference[];
  sections: LessonSection[]; activity: string; check: Check; lab?: boolean;
}
export const sources = {
  intro: 'materials/slides/Lecture1-Introduction to Big Data Analytics.pdf',
  prep: 'materials/slides/Lecture2-Data Preprocessing and Feature Engineering.pdf',
  cluster: 'materials/slides/Lecture3-Clustering.pdf',
  eda: 'materials/labs/Exercise2_data_exploration.ipynb',
  lab: 'materials/labs/Exercise3_clustering.ipynb',
};
export const lessons: Lesson[] = [{
  slug: 'learning-paradigms', title: 'What can a machine learn?',
  summary: 'Start with the information a learner receives, then choose the right kind of learning problem.', minutes: 18,
  objectives: ['Distinguish learning from labels, structure, and rewards.', 'Separate regression from classification.', 'Explain latent representations and self-supervised tasks.'],
  sources: [{ label: 'Lecture 1 · Learning paradigms', path: sources.intro, locator: 'pp. 7–44' }],
  sections: [
    { id: 'targets', title: 'Start with the target', paragraphs: ['Suppose you have previous house sales and want to predict the price of another house. Each training example pairs inputs with an observed price. Supervised learning searches for a mapping between these inputs and outputs.', 'Price is a continuous numerical output, so this is regression. Predicting a music genre is classification because its output is a discrete class. One output is univariate; several outputs are multivariate. A depth map predicts many continuous outputs, one for each pixel.', 'Fit the model on training data and assess predictions on a separate test set. Memorizing the examples used to fit it is not the same as working well on unseen records.'] },
    { id: 'structure', title: 'When there is no supplied label', paragraphs: ['Suppose records have no target attached. Clustering groups similar records; outlier detection asks which records do not fit the usual pattern. These are unsupervised tasks. A cluster is a grouping under a chosen representation and similarity rule, not necessarily a real-world category.', 'Generative models learn structure in data so that they can produce new examples. In a latent-variable model, a hidden variable is mapped to an observation. A GAN generator uses this idea to create a candidate sample.', 'Self-supervised training derives prediction targets from the data itself. This training setup and zero-shot use are different ideas: the latter describes applying a model without task-specific training examples. The lecture introduces these ideas through transformers and language-model training.'] },
    { id: 'rewards', title: 'Learning through consequences', paragraphs: ['An agent learning a game sees a state, chooses an action, and receives rewards. Reinforcement learning gathers experience through interaction. A useful move may pay off much later, creating a credit-assignment problem.', 'Exploration tries uncertain actions to gather information. Exploitation uses what currently seems best. Rewards and state transitions can be stochastic, so repeating an action need not give the same result.', 'The language-model examples also show why data curation matters: a larger model does not make poor data trustworthy. Model sizes and compute-cost figures in the slides describe historical examples, not current prices.'] },
  ], activity: 'paradigms',
  check: { question: 'A model predicts a continuous depth value at every pixel. How should you describe its output?', options: [
    { id: 'multi-regression', label: 'Multivariate regression', correct: true, feedback: 'There are many outputs, and each is a continuous depth. An image input does not make the task classification.' },
    { id: 'image-classification', label: 'Multiclass classification', feedback: 'Multiclass classification selects discrete classes. Depth values are continuous, with one output per pixel.' },
    { id: 'clustering', label: 'Unsupervised clustering', feedback: 'Grouping similar pixels is different from predicting numerical depth from labelled examples.' },
  ] },
}];

lessons.push({
  slug: 'big-data-systems', title: 'Choose a data architecture', minutes: 20,
  summary: 'Separate transactional work from analytics, and decide when a stream needs a faster response.',
  objectives: ['Compare OLTP and OLAP access patterns.', 'Explain ETL and the role of distributed storage and processing.', 'Match batch and streaming architectures to a use case.'],
  sources: [{label:'Lecture 1 · Big data systems',path:sources.intro,locator:'pp. 45–end; course outline pp. 2–3'}],
  sections: [
    {id:'workloads',title:'A sale and a sales report ask different things',paragraphs:['Recording a purchase changes a small number of records and should respond quickly while many customers use the system. This is online transaction processing, OLTP. Summing several years of sales scans far more data and is an analytical workload, OLAP.', 'Running both against the same resources can create conflicting access patterns and variable latency. A data warehouse separates analytical work from user-facing transactions. ETL extracts records, transforms them into a consistent representation, and loads that representation for analysis.'],table:[['Workload','Typical work','Access pattern'],['OLTP','Record an order','Small reads and updates; many users'],['OLAP','Compare sales by country and brand','Scans, joins, and aggregation'],['ETL','Prepare warehouse records','Repeated batch transformation']]},
    {id:'scale',title:'More data changes the bottleneck',paragraphs:['Variety means one application may combine tables, text, graphs, and streams. Velocity concerns how fast observations arrive and how quickly a decision must be made. Volume concerns how much must be stored or processed. A large file and a fast stream do not necessarily need the same system.', 'If processing one day of data takes longer than a day, the backlog grows. The lecture places Hadoop in the batch ETL pipeline: HDFS holds data across machines and a processing framework distributes work. Developers specify a computation while the runtime coordinates execution.', 'Workers still have to exchange information and share resources. Assigning tasks, aggregating partial results, handling failure, and determining completion are real costs. Adding workers does not remove communication or synchronization.']},
    {id:'architectures',title:'Match the architecture to the decision',paragraphs:['An overnight report can use batch ingestion, distributed processing, and export to an analytical database. Logs arriving continuously can still be stored and analyzed in batches if the decision tolerates that delay. The lecture uses Flume for log ingestion and Oozie for workflow scheduling.', 'A query for the latest events from one user needs an indexed real-time store. A system can combine this serving layer with batch analytics. Streaming computation is appropriate when each new event must affect a result promptly. Spark is part of the processing ecosystem introduced in the course, with deeper programming covered in later lectures.', 'Cloud resources can be provisioned on demand. IaaS exposes infrastructure such as virtual machines; PaaS provides a managed application platform; SaaS supplies an application. Virtualization lets operating systems share hardware through a hypervisor. Elasticity is the ability to adjust provisioned capacity as demand changes.']},
  ], activity:'systems', check:{question:'A continuously arriving log is only used for an overnight report. Must every event be analyzed immediately?',options:[
    {id:'batch',label:'No. Store incoming events and process a batch for the report.',correct:true,feedback:'Arrival can be continuous while the analytical workload is batch. The response deadline determines whether immediate processing is needed.'},
    {id:'always-stream',label:'Yes. Any continuously arriving data requires immediate analytics.',feedback:'This confuses ingestion speed with the deadline for the analytical result. The report can tolerate batch processing.'},
    {id:'oltp',label:'Run every report query in the transactional database.',feedback:'Large analytical scans compete with short transactions. The lecture separates these workloads to control latency.'},
  ]},
}, {
  slug:'clean-transform',title:'Make the data comparable',minutes:24,
  summary:'Inspect missing values and noisy records, then see exactly what normalization changes.',
  objectives:['Choose a cleaning action and explain its tradeoff.','Interpret distributions and variable types.','Calculate min-max and z-score transformations.'],
  sources:[{label:'Lecture 2 · Exploration, cleaning, integration',path:sources.prep,locator:'pp. 3–29'}],
  sections:[
    {id:'inspect',title:'Inspect before you transform',paragraphs:['A column of numbers is not automatically a measurement. A district code names a category; averaging district codes has no useful numerical interpretation. Nominal variables have no inherent order. Ordinal variables have an order, while quantitative variables measure discrete counts or continuous values.', 'Mean, median, quartiles, and dispersion describe different aspects of a distribution. A few large observations can pull the mean upward while the median changes little. Plot the observations as well as the summary: different patterns can have similar summary statistics.', 'The interquartile range is Q3 − Q1. Conventional boxplot fences are Q1 − 1.5 × IQR and Q3 + 1.5 × IQR. A point beyond a fence is worth inspecting; being unusual is not proof of an error. Scatterplots reveal relationships that a single correlation coefficient may hide.']},
    {id:'clean',title:'Every cleaning choice makes an assumption',paragraphs:['Missing observations may result from collection errors, inapplicable questions, or different collection and analysis requirements. Dropping incomplete rows is simple but discards data. Filling with a constant, mean, or estimated value keeps rows while introducing assumptions about what is missing.', 'Noise may come from instruments, entry errors, or transmission. Sort and group values into bins to smooth by a mean, median, or boundary. Equal-width bins divide the numerical range; equal-frequency bins aim for a similar number of observations in each bin. Outliers can stretch equal-width bins.', 'When joining sources, resolve both entity identity and representation. The same person can appear under different names, and the same quantity can use different units. Remove redundant attributes only after checking whether they are derived or merely correlated.'],code:'values = [4, 8, 9, 15, 21, 21, 24, 25, 26, 28, 29, 34]\n# Three equal-frequency bins of four values each\nbins = [values[i:i + 4] for i in range(0, len(values), 4)]\nmeans = [sum(group) / len(group) for group in bins]\n# Exact means: 9.0, 22.75, 29.25'} ,
    {id:'scale-values',title:'Change the scale, not the underlying observation',paragraphs:['A distance-based method compares numerical differences. A feature measured in thousands can dominate one measured in units. Normalization changes the numerical representation so that scale reflects your modelling choice.', 'Min-max scaling to [0, 1] uses (x − min) / (max − min). For income 73,000 in a range from 12,000 to 98,000, the result is 61,000 / 86,000 ≈ 0.709. Z-score scaling uses (x − mean) / standard deviation. With mean 54,000 and standard deviation 16,000, the same income becomes 1.1875.', 'Decimal scaling divides by a power of ten until the maximum absolute value is less than one. Transformations also include constructing new attributes and aggregating records. In the lab, extracting hour from a timestamp is feature construction.']},
  ],activity:'normalization',check:{question:'An income of 54,000 is transformed using mean 54,000 and standard deviation 16,000. What is its z-score?',options:[
    {id:'zero',label:'0',correct:true,feedback:'Subtracting the mean gives zero. Z-score zero means the observation is exactly at the reference mean.'},
    {id:'one',label:'1',feedback:'A z-score of one would mean one standard deviation above the mean, or 70,000 in this example.'},
    {id:'half',label:'0.5',feedback:'The midpoint of a min-max range and the mean used by a z-score are different reference values.'},
  ]},
}, {
  slug:'pca',title:'Keep the useful directions',minutes:25,
  summary:'Project a cloud of points and connect retained variance with reconstruction error.',
  objectives:['Distinguish feature selection from extraction.','Explain PCA as a projection of centered data.','Use explained variance to reason about the number of components.'],
  sources:[{label:'Lecture 2 · Reduction and PCA',path:sources.prep,locator:'pp. 31–67'}],
  sections:[
    {id:'reduction',title:'A larger feature set can make learning harder',paragraphs:['With three bins per feature, one feature gives three regions, two give nine, and d features give 3^d. Keeping those regions populated becomes harder as dimensionality increases. More attributes can add noise or redundancy rather than useful information.', 'Feature selection keeps some original attributes. Forward selection adds a useful feature at each step; backward elimination removes a weak one. Feature extraction constructs new coordinates from existing attributes. A principal component is an extracted feature, not a selected input column.', 'Reducing the number of records is a separate decision. Sampling keeps a representative subset; histograms store aggregated counts; clustering can replace groups with representatives. The clustering lab uses mini-cluster centers for this purpose.']},
    {id:'projection',title:'Which line loses the least information?',paragraphs:['Imagine measurements lying close to a diagonal line. You can represent each point by its position along that line. Reconstructing the point on the line introduces a small perpendicular error. Projecting onto the wrong line can lose most of the pattern.', 'PCA centers the data and chooses orthogonal directions of greatest variance. For a fixed number of components, these directions minimize squared reconstruction error. Consider scaling before PCA when input units differ; a high-variance unit can otherwise dominate.', 'Covariance measures how dimensions vary together. Eigenvectors of the covariance matrix give the principal directions, and eigenvalues describe variance along them. In Ax = λx, x is the eigenvector and λ is the eigenvalue.']},
    {id:'components',title:'Keep enough components for your purpose',paragraphs:['Order components by their eigenvalues. The fraction explained by the first k is the sum of their eigenvalues divided by the sum across all components. A cumulative variance plot shows what is retained as k increases.', 'For eigenvalues 8, 1, and 1, the first component retains 80% and the first two retain 90%. Neither percentage is automatically sufficient: the appropriate reduction depends on what the next analysis needs.', 'PCA seeks variance, not class separation. LDA instead uses class information to seek discriminating directions. The lecture also introduces ICA, distance-preserving projections, and nonlinear manifold methods. Do not assume that a visually separated two-dimensional embedding preserves every relationship in the original data.', 'Image patches provide a concrete compression example in the lecture: each 12 × 12 patch is a 144-dimensional vector. Keeping 60 or 16 components uses a smaller representation, with increasing loss as fewer directions remain.']},
  ],activity:'pca',check:{question:'Eigenvalues are 8, 1, and 1. How much total variance do the first two principal components explain?',options:[
    {id:'ninety',label:'90%',correct:true,feedback:'The retained sum is 8 + 1 = 9 and the total is 10, so 9 / 10 = 90%.'},
    {id:'eighty',label:'80%',feedback:'80% is the first component alone. Include the second eigenvalue when retaining two components.'},
    {id:'two-thirds',label:'About 67%',feedback:'Components do not necessarily contribute equally. Use their eigenvalues, not only their count.'},
  ]},
}, {
  slug:'exploration-lab',title:'Lab · Explore the Chicago data',minutes:40,lab:true,
  summary:'Prepare the exploration notebook, choose informative plots, and record evidence for a claim.',
  objectives:['Prepare the notebook’s timestamp and categorical columns.','Select plots for distributions and relationships.','Support a finding with evidence and a limitation.'],
  sources:[{label:'Exercise 2 · Explorative Data Analysis',path:sources.eda,locator:'All notebook sections'},{label:'Lecture 2 · Data exploration',path:sources.prep,locator:'pp. 7–16'}],
  sections:[
    {id:'setup',title:'Start with the supplied data',paragraphs:['The notebook studies Chicago crime data and refers to a compressed 2017 subset in Moodle. That dataset was not included with the supplied course folder. Download it from your course space before running the notebook locally in Jupyter. The browser activity below uses an explicitly synthetic sample.', 'Use the notebook imports for pandas, NumPy, matplotlib, and seaborn. Read the compressed CSV directly with pandas.read_csv, then inspect info() and head(). The provided notebook removes rows with missing values. Record how many are removed and consider what that means for your interpretation.'],code:'import pandas as pd\n\nfile_path = "YOUR_DOWNLOADED_CSV_FILE"\ndf = pd.read_csv(file_path)\nprint(df.info())\nprint(df.head())\nrows_before = len(df)\ndf = df.dropna(how="any").copy()\nprint("Rows removed:", rows_before - len(df))'},
    {id:'features',title:'Represent meaning, not just parser types',paragraphs:['Set ID as the index and remove Case Number. The notebook restricts its analysis to 2017, so Year is constant; Updated On is not part of its analysis. Derive month, day, weekday, and hour from Date.', 'Keep longitude and latitude. Remove the redundant Location, X Coordinate, and Y Coordinate representations. Convert Block, Beat, Community Area, District, and Ward to categories as instructed. Administrative areas should be treated as distinct classifications; do not assume every boundary nests perfectly inside another.', 'Keep Primary Type, Description, Arrest, Domestic, and Location Description as categorical attributes. Remove IUCR and FBI Code for this exercise. A numeric-looking identifier should not become a continuous measurement merely because pandas parsed it as a number.'],code:'stamp = pd.to_datetime(df["Date"], format="%m/%d/%Y %I:%M:%S %p")\ndf["month"] = stamp.dt.month\ndf["day"] = stamp.dt.day\ndf["weekday"] = stamp.dt.dayofweek\ndf["hour"] = stamp.dt.hour\n# Continue the remaining conversions in the original notebook.'},
    {id:'plots',title:'Use a plot that can answer the question',paragraphs:['Use count plots to compare categorical frequencies and quantile plots to inspect how values accumulate across the distribution. Compare hour across crime types or weekdays using boxplots. Violin plots reveal distribution shape but depend on smoothing bandwidth; the notebook asks you to compare 1.0, 0.1, and 0.01.', 'A scatterplot matrix compares pairs of attributes. Sampling and transparency help with dense plots; two-dimensional histograms show density when points overlap. Reordering variables can make relationships easier to notice.', 'The advanced exercises also explore parallel coordinates and correlations. Numeric encodings of categories can create an artificial order, and a correlation pattern does not establish a cause. Record the plotting choices and subset alongside each conclusion.'],table:[['Question','Try','Watch for'],['Which types occur most?','Count plot','Ordering and unequal frequency'],['When do types occur?','Box or violin plot of hour','Small samples and midnight wraparound'],['Where are dense regions?','2D histogram','Bin size and missing coordinates'],['Do attributes vary together?','Scatter matrix or correlation','Category encodings and overplotting']]},
  ],activity:'eda',check:{question:'A district column is stored as integers. Which preparation best matches its meaning in this lab?',options:[
    {id:'category',label:'Treat district as a categorical identifier.',correct:true,feedback:'The numbers identify areas. Their differences and arithmetic mean do not define a meaningful spatial measurement.'},
    {id:'mean',label:'Average the district codes to find the center of the city.',feedback:'Averaging labels does not produce a geographical center. Use meaningful coordinates for spatial calculations.'},
    {id:'scale',label:'Normalize district codes and interpret them as distances.',feedback:'Normalization changes scale, not meaning. Codes remain identifiers after scaling.'},
  ]},
}, {
  slug:'kmeans',title:'Build clusters one step at a time',minutes:25,
  summary:'Follow assignments and centroid updates, and see why a lower squared error is only part of the story.',
  objectives:['Trace k-means assignment and update steps.','Interpret SSE and the role of initialization.','Recognize limitations of centroid-based partitions.'],
  sources:[{label:'Lecture 3 · Partitioning and k-means',path:sources.cluster,locator:'pp. 1–20; pp. 55–57'}],
  sections:[
    {id:'groups',title:'Similarity depends on representation',paragraphs:['Clustering aims for similarity within groups and differences between groups. The number of plausible groups may depend on the scale at which you look. There need not be a single correct partition.', 'K-means represents each cluster with its mean. Start with k centers, assign each point to its nearest center, and recompute each center as the mean of its assigned points. Repeat until the assignments or centers stop changing.']},
    {id:'objective',title:'What exactly gets smaller?',paragraphs:['The sum of squared errors, SSE, adds the squared distance from each point to its assigned center. Assigning to the nearest center minimizes each point’s contribution for fixed centers. Taking the mean minimizes the group’s squared distances for fixed assignments.', 'These alternating steps decrease or preserve the objective but need not find its global minimum. Different initial centers can lead to different partitions. The lab asks you to vary k and initialization settings and inspect both runtime and the result.', 'A centroid summarizes location, not an arbitrary shape. Unequal density, non-globular groups, and outliers can produce misleading partitions. Increasing k often reduces SSE even when the extra groups are not useful.'],code:'repeat:\n    assign each point to its nearest center\n    replace each non-empty cluster center with its mean\n    stop when assignments no longer change\n\nSSE = sum(squared_distance(point, assigned_center))'},
  ],activity:'kmeans',check:{question:'SSE becomes smaller when k increases from 3 to 5. What can you conclude?',options:[
    {id:'only-fit',label:'The five-center representation fits more closely under SSE; usefulness still needs evaluation.',correct:true,feedback:'More centers give the model additional flexibility. A lower SSE alone does not prove that five meaningful groups exist.'},
    {id:'truth',label:'There are exactly five true groups.',feedback:'SSE is an internal fit criterion. It does not reveal a unique real-world group count.'},
    {id:'global',label:'The algorithm has found the global optimum.',feedback:'Initialization can lead to local optima at either k. Comparing SSE values does not certify global optimality.'},
  ]},
}, {
  slug:'density-hierarchy',title:'Beyond round clusters',minutes:25,
  summary:'Compare irreversible merges with density-connected groups, including points that do not belong.',
  objectives:['Compare single, complete, average, and Ward linkage.','Identify DBSCAN core, border, and noise points.','Explain the effects of epsilon and minimum points.'],
  sources:[{label:'Lecture 3 · Hierarchical and density clustering',path:sources.cluster,locator:'pp. 21–43'}],
  sections:[
    {id:'merge',title:'Build a hierarchy of merges',paragraphs:['Agglomerative clustering starts with individual points as clusters. At each step, merge the two closest clusters and update the proximity matrix. A dendrogram records that sequence, and cutting it at a chosen level gives a partition.', 'The linkage rule defines what closest means. Single linkage uses the minimum pairwise distance, complete linkage the maximum, and average linkage an average across pairs. Ward’s method chooses the merge with the smallest increase in within-cluster squared error.', 'A merge is not undone later. Different linkage rules therefore create different hierarchies. Pairwise proximity storage and repeated merge decisions can be expensive for large datasets.'],table:[['Rule','Distance or cost','What to inspect'],['Single','Nearest cross-cluster pair','Chains joining groups'],['Complete','Farthest cross-cluster pair','Compactness and outliers'],['Average','Average cross-cluster pair','Overall cross-group separation'],['Ward','Increase in squared error','Preference for globular groups']]},
    {id:'density',title:'A cluster can follow dense neighborhoods',paragraphs:['DBSCAN describes density using a radius ε and a minimum number of observations, MinPts. In this activity a neighborhood includes the point itself, and at least MinPts observations make it a core point. This makes the threshold convention explicit.', 'Core points within ε connect dense regions. A border point has too few neighbors to be core but lies near a core point. A noise point is neither core nor border. Border points do not themselves extend a chain into another region.', 'Small ε can label many points as noise; large ε can join groups that you wanted to separate. The lecture suggests examining sorted k-nearest-neighbor distances for a knee when choosing parameters. There may be no clear knee, especially with varying densities.']},
    {id:'limits',title:'Different strengths, different failure modes',paragraphs:['Density-based clustering can follow non-round shapes and leave observations unassigned. A single global density threshold can struggle when genuine groups have different densities. High-dimensional distances and parameter sensitivity also deserve inspection.', 'A border point may be reachable from more than one cluster. Implementations need a consistent assignment rule. The demonstration assigns it to the first reachable cluster in point order; the lecture’s pseudocode describes a nearest-core rule. Both preserve the distinction between core, border, and noise, but boundary assignments can differ.']},
  ],activity:'dbscan',check:{question:'A point has too few neighbors to be core, but it lies within ε of a core point. What is it?',options:[
    {id:'border',label:'A border point',correct:true,feedback:'A border point joins a dense region through a core point, even though its own neighborhood does not meet MinPts.'},
    {id:'noise',label:'Noise',feedback:'Noise is not reachable directly from a core neighborhood. This point is within ε of a core point.'},
    {id:'core',label:'A core point',feedback:'Being near a core point is insufficient to become core. Its own neighborhood must meet the threshold.'},
  ]},
}, {
  slug:'cluster-validation',title:'Are these clusters useful?',minutes:22,
  summary:'Separate internal structure from agreement with known labels, and calculate what the scores actually measure.',
  objectives:['Distinguish internal, external, and relative validation.','Calculate SSE, purity, and silhouette on small examples.','Explain why a validation score needs context.'],
  sources:[{label:'Lecture 3 · Cluster validity',path:sources.cluster,locator:'pp. 44–64'}],
  sections:[
    {id:'evidence',title:'First ask what evidence you have',paragraphs:['An internal index evaluates a partition using the data, such as within-cluster squared error. An external index compares the partition with supplied reference labels. A relative comparison uses an index to compare candidate clusterings.', 'Clustering tendency asks whether non-random structure exists in the first place. An algorithm can partition random data, so a numerical score needs context. Compare representations and parameter settings and inspect whether differences are meaningful.']},
    {id:'external',title:'Agreement is more than one kind of match',paragraphs:['Purity counts the largest reference-label group in each cluster, sums those counts, and divides by the number of observations. For example, majority counts 30, 20, and 25 out of 100 observations, giving purity 0.75. Splitting into many small clusters can inflate purity.', 'Maximum matching restricts the correspondence between clusters and reference groups. Precision and recall capture different aspects of overlap; their harmonic mean is the F-measure. Conditional entropy measures how mixed reference labels remain inside clusters.', 'Pairwise measures compare pairs of observations. A true positive pair is together in both partitions; a false positive pair is together only in the clustering; a false negative pair is together only in the reference. Jaccard is TP / (TP + FP + FN), while Rand also counts true negatives.']},
    {id:'internal',title:'Compactness and separation need to be read together',paragraphs:['For observations 1, 2, 4, and 5, two groups {1,2} and {4,5} have centers 1.5 and 4.5. WSS is four terms of 0.25, totaling 1. With grand mean 3, BSS is 2 × 1.5² + 2 × 1.5² = 9. Their sum is the total squared deviation, 10.', 'The elbow heuristic looks for a diminishing improvement in SSE as k grows. It is a judgement about a curve, not a guarantee of a unique group count. BetaCV compares average within-cluster and between-cluster distances.', 'For a point, let a be its average distance to other points in its own cluster and b the smallest average distance to another cluster. Silhouette is (b − a) / max(a, b). Values near 1 favor the assignment, near 0 indicate a boundary, and negative values suggest a closer alternative. Its full range is −1 to 1.', 'Reordering a similarity matrix by cluster labels can reveal block structure. If the matrix holds distances rather than similarities, nearby points have small values: interpret correlation signs accordingly. Non-globular clusters may not fit compactness-based criteria well.']},
  ],activity:'silhouette',check:{question:'A point has a = 4 and b = 2. What does its silhouette of −0.5 suggest?',options:[
    {id:'alternative',label:'It is closer on average to another cluster than to its assigned cluster.',correct:true,feedback:'b is smaller than a. The negative score flags a potentially poor assignment, rather than strong cohesion.'},
    {id:'strong',label:'It is strongly separated in its assigned cluster.',feedback:'Strong separation requires b to exceed a. Here the alternative cluster is closer on average.'},
    {id:'impossible',label:'The score is impossible because silhouettes cannot be negative.',feedback:'Silhouette ranges from −1 to 1. Negative values are possible when another cluster is closer on average.'},
  ]},
}, {
  slug:'clustering-lab',title:'Lab · Compare clustering methods',minutes:45,lab:true,
  summary:'Prepare the GeoNames notebook and compare six methods using a consistent experimental record.',
  objectives:['Explain the notebook’s 3D geographic representation and aggregation.','Identify parameters for each clustering method.','Compare runtime and partition behavior without treating the map as ground truth.'],
  sources:[{label:'Exercise 3 · Clustering',path:sources.lab,locator:'Preprocessing, aggregation, and all six clustering sections'}],
  sections:[
    {id:'geo',title:'The map is not the space being clustered',paragraphs:['The notebook uses GeoNames inhabited places. It filters non-positive population and converts longitude and latitude into three-dimensional coordinates on the WGS84 reference ellipsoid. The clustering operates on x, y, z; longitude and latitude are used to display the result.', 'The full dataset is aggregated with MiniBatchKMeans into 2,048 representative centers. Later algorithms cluster those centers, then a sparse transfer matrix maps their labels back to the original records for plotting.', 'The preprocessed files referenced in Moodle are not in the supplied folder. Obtain them there, or follow the notebook’s optional raw-data preprocessing. Validate the file checksums before running comparisons.']},
    {id:'methods',title:'Change one choice at a time',paragraphs:['Keep the input representation and observation set fixed when comparing parameters. Record whether StandardScaler is active: the notebook’s DBSCAN comparison deliberately disables scaling. Its ε therefore has a different numerical meaning from an ε chosen after scaling.', 'Start with the k-means loop over k = 3 through 7. Then compare Gaussian mixtures, spectral clustering, agglomerative clustering, DBSCAN, and mean shift using the parameters below. The notebook leaves several parameter variables for you to define.', 'These are notebook experiments, not browser Python execution. Open the original notebook for its helper functions and plots. The browser simulation in the earlier modules is a small educational implementation using synthetic points.'],table:[['Method','Parameters to vary','Question to investigate'],['K-means','n_clusters, n_init','Do centers and assignments stabilize?'],['Gaussian mixture / EM','n_components, covariance_type','How does covariance shape change the partition?'],['Spectral','n_clusters, n_neighbors','What changes when neighborhood connectivity changes?'],['Agglomerative','n_clusters, linkage','How do merge rules change groups?'],['DBSCAN','eps, min_samples','Which regions are dense enough; how much noise remains?'],['Mean shift','bandwidth, bin_seeding','How does the density scale change the number of groups?']]},
    {id:'record',title:'Make a comparison someone else can inspect',paragraphs:['For each run, record parameters, scaling, elapsed time, group count, any noise count, and one concrete observation from the plot. Explain a change using the method’s mechanism rather than describing colors alone.', 'The original notebook reflects the APIs used when it was written. For example, agglomerative clustering uses an affinity argument in the source; check the signature installed in your lab environment if this raises an error. Keep the original file as evidence and make your working edits in a copy.', 'Compare a fast method and a slower method on the same data. Does the additional computation reveal a structure that matters for your question? Record a limitation, including distortion in the displayed map or differences between density-based and centroid-based objectives.'],code:'# Suggested experiment record; use with the original notebook\nresults = []\n# After each run, append your measured values and interpretation:\n# results.append({\n#   "method": "KMeans", "parameters": {"n_clusters": 3},\n#   "scaling": True, "seconds": measured_seconds,\n#   "observation": "...", "limitation": "..."\n# })'},
  ],activity:'lab-record',check:{question:'Why can a clustering on 3D coordinates look distorted in the longitude-latitude plot?',options:[
    {id:'projection',label:'The displayed coordinates differ from the space used to compute distances.',correct:true,feedback:'The notebook clusters WGS84-derived x, y, z and then maps labels back to a longitude-latitude display. Visual map distances do not directly equal the clustering distances.'},
    {id:'labels',label:'The longitude and latitude are the class labels.',feedback:'They are plotting coordinates. This unsupervised experiment does not use those coordinates as ground-truth class labels.'},
    {id:'same',label:'It cannot; the map must preserve every 3D distance.',feedback:'A two-dimensional longitude-latitude view is not a distance-preserving display of the three-dimensional representation.'},
  ]},
});
